# Generated by Django 5.0.7 on 2024-08-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileuploadhistory',
            options={'verbose_name_plural': 'File Upload History'},
        ),
        migrations.AlterField(
            model_name='fileuploadhistory',
            name='input_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='fileuploadhistory',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
